### ISSUE TITLE
CSV: Add field to set userId & localpart

### ISSUE THREAD

**Issue by nikzen** [famedly/famedly-sync#96]
### Description
To migrate our remaining customers from LDAP to Zitadel, we need to reuse the localpart. 

### Solution
Add an extra field in the csv which is used to set the userId and localpart usermtadata.

**Comment by tlater-famedly** [comment]
>   "userId": "localpart-value",

Hm, we have this problem in general, but since syncing requires knowing the original sources' ID we'll need to come up with some clever way to match user IDs if they don't match whatever database we sync from in the future (assuming a different sync method ends up being used after an initial CSV sync).

**Comment by emgrav** [comment]
For now we will reiterate and make even clearer that switching from one sync method to another is unsupported.

**Comment by jannden** [comment]
See also https://github.com/famedly/famedly-sync/issues/75
